name: e2e-tests
on: [push]
jobs:
    cypress-run:
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout
              uses: actions/checkout@v4
            - name: cypress run
              uses: cypress-io/github-actions@v6
              with:
                start: npm start
                spec: cypress/e2e/LoginTest.cy.js